version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=bookstore_project.settings.prod
    depends_on:
      - db
    
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=bookstorepass
      - POSTGRES_DB=bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
